### ISSUE TITLE
KeyError: 'ATDB'

### ISSUE THREAD

**Issue by hexauniverse** [rickh94/airtable_local_backup#1]
```
C:\Users\8350690\Desktop\a\b>python3 run.py
Traceback (most recent call last):
  File "run.py", line 10, in <module>
    BASE = os.environ['ATDB']
  File "C:\Users\8350690\AppData\Local\Programs\Python\Python37-32\lib\os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'ATDB'
```

**Comment by dkrylovsb** [comment]
Set the `ATDB` environment variable to AirTable base key (e.g. `appXZYtTtmCwA9zAA`)

**Comment by hexauniverse** [comment]
thanks, i understood. I don't need it already
